apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: production
  labels:
    tier: production
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: production
      app: mongo
  template:
    metadata:
      labels:
        tier: production
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
             memory: "512Mi"
             cpu: "1000m"  
          volumeMounts:
            - name: mongodb-prod-pv
              mountPath: /data/db
          livenessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.runCommand({ ping: 1 })"
            initialDelaySeconds: 30
            periodSeconds: 10
      nodeSelector:
        tier: production
      tolerations:
       - key: "tier"
         operator: "Equal"
         value: "production"
         effect: "NoSchedule"
      volumes:
      - name: mongodb-prod-pv
        persistentVolumeClaim:
          claimName: pvc-mongo