apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  namespace: production
spec:
  storageClassName: ""
  resources:
    requests:
       storage: 5Gi
  volumeMode: Filesystem
  volumeName: pv-redis
  accessModes:
    - ReadWriteOnce