apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  namespace: production
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
   path: /data/redis