apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-redis
  name: redis-service
  namespace: production
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    # nodePort: 32666
  selector:
    app: deployment-redis
  type: ClusterIP